# Copyright 2026 Firefly Software Solutions Inc
"""ASGI entry point for flydesk-idp.

Loaded by ``pyfly run`` and by ``uvicorn flydesk_idp.main:app``. Builds
the :class:`PyFlyApplication`, scans every ``@rest_controller`` /
``@configuration`` / ``@service`` / ``@controller_advice`` /
``@command_handler`` / ``@query_handler`` under ``flydesk_idp``, and
returns a FastAPI app with all routes mounted, the actuator + admin
exposed, exception handlers wired, and the OpenAPI spec generated by
pyfly's introspector (not FastAPI's default, which can't see through
the lazy-resolution route shim).
"""

from __future__ import annotations

from contextlib import asynccontextmanager
from typing import Any

from pyfly.core import PyFlyApplication
from pyfly.web.adapters.fastapi.app import create_app

from flydesk_idp import __version__
from flydesk_idp.app import FlydeskIDPApplication
from flydesk_idp.web.correlation_filter import CorrelationHeadersMiddleware
from flydesk_idp.web.openapi_override import install_openapi

_TITLE = "flydesk-idp"
_DESCRIPTION = (
    "Intelligent Document Processing for Firefly Desk -- pure-multimodal "
    "field extraction with normalised bounding boxes, deterministic "
    "StandardValidators, LLM judge cross-check, and a DAG business-rule "
    "engine. Synchronous (`POST /api/v1/extract`) and queue-backed "
    "asynchronous (`POST /api/v1/jobs`) APIs."
)

# Build PyFlyApplication: loads pyfly.yaml, scans packages, prepares the DI context.
_pyfly = PyFlyApplication(FlydeskIDPApplication)


@asynccontextmanager
async def _lifespan(app: Any):
    """Drive the framework's startup / shutdown lifecycle.

    Also installs the pyfly-driven OpenAPI generator after startup, so
    Swagger / ReDoc see the real controller signatures (tags, request
    bodies, response models) instead of the lazy-resolution shim that
    pyfly registers with FastAPI.
    """
    _pyfly._route_metadata = getattr(app.state, "pyfly_route_metadata", [])
    _pyfly._docs_enabled = getattr(app.state, "pyfly_docs_enabled", False)
    _pyfly._host = str(_pyfly.config.get("pyfly.web.host", "0.0.0.0"))
    _pyfly._port = int(_pyfly.config.get("pyfly.server.port", 8400))
    await _pyfly.startup()
    install_openapi(
        app,
        _pyfly.context,
        title=_TITLE,
        version=__version__,
        description=_DESCRIPTION,
    )
    yield
    await _pyfly.shutdown()


app = create_app(
    title=_TITLE,
    version=__version__,
    description=_DESCRIPTION,
    context=_pyfly.context,
    docs_enabled=True,
    actuator_enabled=True,
    lifespan=_lifespan,
)
# Correlation surface (X-Correlation-Id / X-Request-Id / X-Tenant-Id /
# W3C traceparent / tracestate). Registered AFTER create_app so it sits
# in front of pyfly's WebFilterChainMiddleware -- the inbound request
# hits the correlation middleware first, gets stamped, then enters the
# pyfly chain (TransactionIdFilter, request logging, etc.).
app.add_middleware(CorrelationHeadersMiddleware)
