# Copyright 2026 Firefly Software Solutions Inc
"""ASGI entry point for flydesk-idp.

Loaded by ``pyfly run`` and by ``uvicorn flydesk_idp.main:app``. Builds
the :class:`PyFlyApplication`, scans every ``@rest_controller`` /
``@configuration`` / ``@service`` / ``@controller_advice`` /
``@command_handler`` / ``@query_handler`` under ``flydesk_idp``, and
returns a FastAPI app with all routes mounted, the actuator + admin
exposed, exception handlers wired, and the OpenAPI spec generated by
pyfly's introspector (not FastAPI's default, which can't see through
the lazy-resolution route shim).
"""

from __future__ import annotations

from contextlib import asynccontextmanager
from typing import Any

from pyfly.core import PyFlyApplication
from pyfly.web.adapters.fastapi.app import create_app

from flydesk_idp import __version__
from flydesk_idp.app import FlydeskIDPApplication
from flydesk_idp.web.openapi_override import install_openapi

_TITLE = "flydesk-idp"
_DESCRIPTION = (
    "Intelligent Document Processing for Firefly Desk -- pure-multimodal "
    "field extraction with normalised bounding boxes, deterministic "
    "StandardValidators, LLM judge cross-check, and a DAG business-rule "
    "engine. Synchronous (`POST /api/v1/extract`) and queue-backed "
    "asynchronous (`POST /api/v1/jobs`) APIs."
)

# Build PyFlyApplication: loads pyfly.yaml, scans packages, prepares the DI context.
_pyfly = PyFlyApplication(FlydeskIDPApplication)


@asynccontextmanager
async def _lifespan(app: Any):
    """Drive the framework's startup / shutdown lifecycle.

    Also installs the pyfly-driven OpenAPI generator after startup, so
    Swagger / ReDoc see the real controller signatures (tags, request
    bodies, response models) instead of the lazy-resolution shim that
    pyfly registers with FastAPI.
    """
    # PyFlyApplication exposes route metadata + host/port via private
    # attributes that the framework's own lifespan flow writes to; we
    # mirror that here so pyfly's structured-logging "server_started"
    # event reports the right host/port. ``setattr`` keeps pyright
    # quiet about writes to attrs that aren't declared on the class --
    # the framework reads them via ``getattr(..., default)`` so missing
    # attrs are always safe.
    # Ruff prefers direct assignment (B010); pyright rejects it because
    # the framework class doesn't declare these attrs. We suppress the
    # ruff rule on each line and keep ``setattr`` -- the standard
    # escape hatch for legitimate dynamic attribute writes.
    setattr(_pyfly, "_route_metadata", getattr(app.state, "pyfly_route_metadata", []))  # noqa: B010
    setattr(_pyfly, "_docs_enabled", getattr(app.state, "pyfly_docs_enabled", False))  # noqa: B010
    setattr(_pyfly, "_host", str(_pyfly.config.get("pyfly.web.host", "0.0.0.0")))  # noqa: B010
    setattr(_pyfly, "_port", int(_pyfly.config.get("pyfly.server.port", 8400)))  # noqa: B010
    await _pyfly.startup()
    # Re-scan HealthIndicator beans now that the container has built
    # every singleton (the eager scan inside ``create_app`` runs BEFORE
    # context startup and would otherwise miss every indicator wired
    # through @auto_configuration). Exposed on app.state by pyfly.
    rescan = getattr(app.state, "pyfly_install_health_indicators", None)
    if callable(rescan):
        rescan()
    install_openapi(
        app,
        _pyfly.context,
        title=_TITLE,
        version=__version__,
        description=_DESCRIPTION,
    )
    yield
    await _pyfly.shutdown()


app = create_app(
    title=_TITLE,
    version=__version__,
    description=_DESCRIPTION,
    context=_pyfly.context,
    docs_enabled=True,
    actuator_enabled=True,
    lifespan=_lifespan,
)
# The W3C correlation surface (X-Correlation-Id / X-Request-Id /
# X-Tenant-Id / traceparent / tracestate) is wired into pyfly's default
# WebFilter chain since pyfly 26.5.5 via
# ``pyfly.web.adapters.starlette.filters.CorrelationFilter`` -- no
# extra middleware to register here.
